name: rugliderqc
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=1.0.1
  - ioos_qc=2.1.0
  - netcdf4=1.7.1
  - numpy=2.0.2
  - pandas=2.2.3
  - python=3.12.5
  - scipy=1.14.1
  - xarray=2024.9.0
  - gsw=3.6.19
  - pyco2sys=1.8.3.3
