name: rugliderqc
channels:
  - conda-forge
  - defaults
dependencies:
  - fiona=1.8.20
  - geopandas=0.9.0
  - ioos_qc=2.0.1
  - netcdf4=1.5.7
  - numpy=1.20.3
  - pandas=1.3.2
  - python=3.9.7
  - scipy=1.7.1
  - xarray=0.19.0
  - gsw=3.4.0
